#! /bin/bash

# Nevermind looks like this problem has already been solved
#
# http://binaryadventures.com/blog/migrating-from-gitolite-to-gitlab/
# 
# https://gist.github.com/benoitzohar/57a93f8edc2a679e360e
# https://forum.gitlab.com/t/migrate-repositories-from-gitolite-to-gitlab/36
